INSERT INTO "PUBLIC"."TREATMENT_DICT" ( "ID", "LABEL" ) VALUES ( 1, 'Zabieg nr 1')
INSERT INTO "PUBLIC"."TREATMENT_DICT" ( "ID", "LABEL" ) VALUES ( 2, 'Zabieg nr 2')

INSERT INTO "PUBLIC"."SPECIALIZATION_DICT" ( "ID", "LABEL" ) VALUES ( 1, 'Specjalizacja nr1')
INSERT INTO "PUBLIC"."SPECIALIZATION_DICT" ( "ID", "LABEL" ) VALUES ( 2, 'Specjalizacja nr2')